const styles = {
  container: {
    //backgroundColor: '#7CB6AC',
    backgroundColor: "#FFFFFF",
    padding: 20,
    flex: 1,
  },
  buttonContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: "8%",
    //alignItems: 'center',
    // paddingBottom: insets.bottom,
  },
  buttonText: {
    textAlign: "center",
  },
  textField: {
    paddingBottom: 5,
    paddingTop: 10,
    fontFamily: "RBlack",
    fontSize: 16,
  },
  textInput: {
    paddingLeft: 10,
    paddingTop: 5,
    paddingBottom: 5,
    width: "92%",
    paddingRight: 5,
    fontFamily: "RR",
  },
  fields: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderColor: "#000000",
    borderWidth: 1,
    borderRadius: 50,
    height: 50,
  },
  buttonNotCompleted: {
    borderRadius: 50,
    alignItems: "center",
    marginBottom: 10,
    marginTop: 10,
    backgroundColor: "#FFFFFF",
    borderColor: "#CECFD3",
    borderWidth: 1,
    height: 50,
    flexDirection: "row",
  },
  buttonCompleted: {
    borderRadius: 50,
    alignItems: "center",
    marginBottom: 10,
    marginTop: 10,
    backgroundColor: "#44A1FE",
    borderColor: "#44A1FE",
    borderWidth: 1,
    height: 50,
    flexDirection: "row",
  },
  buttonPlatform: {
    borderRadius: 50,
    alignItems: "center",
    marginBottom: 10,
    marginTop: 10,
    backgroundColor: "#1777F1",
    borderColor: "#1777F1",
    borderWidth: 1,
    flexDirection: "row",
    height: 50,
  },
};

export default styles;
