const info = {
  default: [
    { label: 'Si', value: true },
    { label: 'No', value: false },
  ],
  sex: [
    { label: 'Masculino', value: 0 },
    { label: 'Femenino', value: 1 },
    { label: 'Otro', value: 2 },
  ],
  race: [
    { label: 'Caucásica', value: 0 },
    { label: 'Africana', value: 1 },
    { label: 'Mongólica', value: 2 },
    { label: 'Amerindia', value: 3 },
    { label: 'Prefiero no decir', value: 4 },
  ],
  bloodType: [
    { label: 'A+', value: 0 },
    { label: 'A-', value: 1 },
    { label: 'B+', value: 2 },
    { label: 'B-', value: 3 },
    { label: 'AB+', value: 4 },
    { label: 'AB-', value: 5 },
    { label: 'O+', value: 6 },
    { label: 'O-', value: 7 },
  ],
  timesDay: [
    { label: '0', value: 0 },
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
    { label: '6', value: 6 },
    { label: '7', value: 7 },
  ],
  timesWeek: [
    { label: '0', value: 0 },
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
    { label: '6', value: 6 },
    { label: '7', value: 7 },
    { label: '8', value: 8 },
    { label: '9', value: 9 },
    { label: '10', value: 10 },
    { label: '11', value: 11 },
    { label: '12', value: 12 },
    { label: '13', value: 13 },
    { label: '14', value: 14 },
    { label: '15', value: 15 },
    { label: '16', value: 16 },
    { label: '17', value: 17 },
    { label: '18', value: 18 },
    { label: '19', value: 19 },
    { label: '20', value: 20 },
    { label: '21', value: 21 },
    { label: '22', value: 22 },
    { label: '23', value: 23 },
    { label: '24', value: 24 },
    { label: '25', value: 25 },
    { label: '26', value: 26 },
    { label: '27', value: 27 },
    { label: '28', value: 28 },
    { label: '29', value: 29 },
    { label: '30', value: 30 },
    { label: '31', value: 31 },
    { label: '32', value: 32 },
    { label: '33', value: 33 },
    { label: '34', value: 34 },
    { label: '35', value: 35 },
    { label: '36', value: 36 },
    { label: '37', value: 37 },
    { label: '38', value: 38 },
    { label: '39', value: 39 },
    { label: '40', value: 40 },
    { label: '41', value: 41 },
    { label: '42', value: 42 },
    { label: '43', value: 43 },
    { label: '44', value: 44 },
    { label: '45', value: 45 },
    { label: '46', value: 46 },
    { label: '47', value: 47 },
    { label: '48', value: 48 },
    { label: '49', value: 49 },
    { label: '50', value: 50 },
    { label: '51', value: 51 },
    { label: '52', value: 52 },
  ],
  diseases: [
    { label: 'Física', value: 0 },
    { label: 'Intelectual', value: 1 },
    { label: 'Mental', value: 2 },
    { label: 'Psicosocial', value: 3 },
    { label: 'Múltiple', value: 4 },
    { label: 'Sensorial', value: 5 },
    { label: 'Auditiva', value: 6 },
    { label: 'Visual', value: 7 },
    { label: 'Otro', value: 8 },
  ],
  pills: [
    { label: '0', value: 0 },
    { label: '1', value: 1 },
    { label: '2', value: 2 },
    { label: '3', value: 3 },
    { label: '4', value: 4 },
    { label: '5', value: 5 },
    { label: '6', value: 6 },
  ],
  placeholder: {
    label: 'Seleccionar...',
    value: undefined,
    color: 'red',
  },
  type: [
    { label: 'Información Básica', value: 0 },
    { label: 'Alergias', value: 1 },
    { label: 'Discapacidades', value: 2 },
    { label: 'Cirugias', value: 3 },
    { label: 'Condiciones', value: 4 },
  ],
  type2: [
    { label: 'Alergias', value: 1 },
    { label: 'Discapacidades', value: 2 },
    { label: 'Cirugias', value: 3 },
    { label: 'Condiciones', value: 4 },
  ],
  filterGraph: [
    { label: 'Semana', value: 1 },
    { label: 'Mes', value: 2 },
  ],
  filterGraphMonthly: [
    { label: 'Enero', value: 1 },
    { label: 'Febrero', value: 2 },
    { label: 'Marzo', value: 3 },
    { label: 'Abril', value: 4 },
    { label: 'Mayo', value: 5 },
    { label: 'Junio', value: 6 },
    { label: 'Julio', value: 7 },
    { label: 'Agosto', value: 8 },
    { label: 'Septiembre', value: 9 },
    { label: 'Octubre', value: 10 },
    { label: 'Noviembre', value: 11 },
    { label: 'Diciembre', value: 12 },
  ],
  filterGraphWeekly: [
    { label: 'Semana 1', value: 1 },
    { label: 'Semana 2', value: 2 },
    { label: 'Semana 3', value: 3 },
    { label: 'Semana 4', value: 4 },
    { label: 'Semana 5', value: 5 },
  ],
  filterGraphYearly: [
    { label: '2019', value: 1 },
    { label: '2020', value: 2 },
    { label: '2021', value: 3 },
    { label: '2022', value: 4 },
    { label: '2023', value: 5 },
  ],
  defaultText: 'Sin registro',
  host: 'http://192.168.1.67:8080',
  APIHost: 'http://medmatter.ngrok.dev/ai',
}

export default info;